sonar.projectKey=shopping_list
sonar.projectName=Shopping_list
sonar.host.url=http://localhost:9000
sonar.sources=src
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/node_modules/**,**/dist/**,**/build/**,**/coverage/**